### ISSUE TITLE
enhancement - integration with vscode

### ISSUE THREAD

**Issue by johndpope** [KelvinJin/iSwift.Linux#2]
https://github.com/johndpope/vscodeJupyter

**Comment by KelvinJin** [comment]
Interesting idea. I know there're bunch of vscode [plugin](https://github.com/jinmingjian/sde) that supports Swift. I guess this project is more aiming to support swift coding/playgound on the Web.

**Comment by johndpope** [comment]
you maybe able to cherry pick this / definitely try it - it's awesome. 
runs right in the app.
https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyter
